import { ApiRequest } from '@desktop/types/api';

export type ResponseFormatMode = 'AUTO' | 'JSON' | 'HTML' | 'XML' | 'TEXT';

const REQUEST_NAME_FALLBACK = 'Untitled Request';

export const deriveRequestNameFromUrl = (url: string) => {
  const value = url.trim();
  if (!value) return REQUEST_NAME_FALLBACK;

  const withoutProtocol = value.replace(/^[a-zA-Z][a-zA-Z\d+\-.]*:\/\//, '');
  const [withoutQuery] = withoutProtocol.split('?');
  const normalized = withoutQuery.replace(/\/$/, '');

  return normalized || withoutProtocol || value;
};

export const shouldSyncRequestNameWithUrl = (name: string, previousUrl: string) => {
  const normalizedName = name.trim();

  if (!normalizedName) {
    return true;
  }

  if (normalizedName === REQUEST_NAME_FALLBACK || normalizedName === 'My First Request') {
    return true;
  }

  return normalizedName === deriveRequestNameFromUrl(previousUrl);
};

export const getAutoGeneratedHeaders = (request: ApiRequest): Record<string, string> => {
  const headers: Record<string, string> = {
    Accept: '*/*',
  };

  if (
    !['GET', 'HEAD'].includes(request.method) &&
    request.bodyType !== 'none' &&
    (request.bodyType === 'json' || request.bodyType === 'graphql')
  ) {
    headers['Content-Type'] = 'application/json';
  }

  if (request.auth.type === 'bearer' && request.auth.token) {
    headers.Authorization = `Bearer ${request.auth.token}`;
  } else if (request.auth.type === 'basic' && request.auth.username) {
    headers.Authorization = `Basic ${btoa(`${request.auth.username}:${request.auth.password || ''}`)}`;
  } else if (request.auth.type === 'api-key' && request.auth.key) {
    headers[request.auth.key] = request.auth.value || '';
  }

  return headers;
};

export const resolveResponseFormat = (
  body: string,
  headers: Record<string, string>,
  selectedFormat: ResponseFormatMode,
): Exclude<ResponseFormatMode, 'AUTO'> => {
  if (selectedFormat !== 'AUTO') {
    return selectedFormat;
  }

  const contentTypeKey = Object.keys(headers).find(key => key.toLowerCase() === 'content-type');
  const contentType = (contentTypeKey ? headers[contentTypeKey] : '').toLowerCase();

  if (contentType.includes('application/json') || contentType.includes('+json')) {
    return 'JSON';
  }

  if (contentType.includes('text/html')) {
    return 'HTML';
  }

  if (contentType.includes('application/xml') || contentType.includes('text/xml') || contentType.includes('+xml')) {
    return 'XML';
  }

  const trimmed = body.trim();
  if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
    return 'JSON';
  }

  if (trimmed.startsWith('<!doctype html') || trimmed.startsWith('<html')) {
    return 'HTML';
  }

  if (trimmed.startsWith('<')) {
    return 'XML';
  }

  return 'TEXT';
};

const formatXmlLike = (source: string) => {
  const content = source.replace(/(>)(<)(\/*)/g, '$1\n$2$3').trim();
  const lines = content.split('\n');
  let indentLevel = 0;

  return lines
    .map(line => {
      if (/^<\//.test(line)) {
        indentLevel = Math.max(indentLevel - 1, 0);
      }

      const formatted = `${'  '.repeat(indentLevel)}${line}`;

      if (/^<[^!?][^>]*[^\/]>/i.test(line) && !line.includes('</')) {
        indentLevel += 1;
      }

      return formatted;
    })
    .join('\n');
};

export const formatResponseBody = (body: string, format: Exclude<ResponseFormatMode, 'AUTO'>) => {
  if (format === 'JSON') {
    try {
      return JSON.stringify(JSON.parse(body), null, 2);
    } catch {
      return body;
    }
  }

  if (format === 'XML' || format === 'HTML') {
    return formatXmlLike(body);
  }

  return body;
};
