import React from 'react';
import { Send, Loader2, Plus, Trash2, GripVertical } from 'lucide-react';
import { useApp } from '@desktop/context/AppContext';
import { cn } from '@/lib/utils';
import { HttpMethod, METHOD_COLORS, KeyValuePair } from '@desktop/types/api';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  deriveRequestNameFromUrl,
  getAutoGeneratedHeaders,
  shouldSyncRequestNameWithUrl,
} from '@desktop/lib/request-utils';

const METHODS: HttpMethod[] = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'];
const AUTH_TYPES = ['none', 'bearer', 'basic', 'api-key'] as const;

const RequestPanel = () => {
  const { state, dispatch, sendRequest } = useApp();
  const activeRequest = state.activeTabId ? state.requests[state.activeTabId] : null;
  const isLoading = state.activeTabId ? state.loading[state.activeTabId] : false;
  const autoGeneratedHeaders = activeRequest ? getAutoGeneratedHeaders(activeRequest) : {};

  if (!activeRequest) {
    return (
      <div className="flex-1 flex items-center justify-center text-muted-foreground">
        <div className="text-center">
          <p className="text-sm font-medium">No request selected</p>
          <p className="text-xs mt-1">Open a request from the sidebar or create a new one</p>
        </div>
      </div>
    );
  }

  const update = (partial: Partial<typeof activeRequest>) => {
    dispatch({ type: 'UPDATE_REQUEST', payload: { ...activeRequest, ...partial } });
  };

  const updateKeyValue = (
    field: 'headers' | 'params',
    id: string,
    updates: Partial<KeyValuePair>
  ) => {
    const list = activeRequest[field].map(item =>
      item.id === id ? { ...item, ...updates } : item
    );
    update({ [field]: list });
  };

  const addKeyValue = (field: 'headers' | 'params') => {
    update({
      [field]: [...activeRequest[field], { id: crypto.randomUUID(), key: '', value: '', enabled: true }],
    });
  };

  const removeKeyValue = (field: 'headers' | 'params', id: string) => {
    update({ [field]: activeRequest[field].filter(item => item.id !== id) });
  };

  const reorderKeyValue = (field: 'headers' | 'params', fromIndex: number, toIndex: number) => {
    if (fromIndex === toIndex || fromIndex < 0 || toIndex < 0 || toIndex >= activeRequest[field].length) {
      return;
    }

    const reordered = [...activeRequest[field]];
    const [moved] = reordered.splice(fromIndex, 1);

    if (!moved) {
      return;
    }

    reordered.splice(toIndex, 0, moved);
    update({ [field]: reordered });
  };

  return (
    <div className="flex-1 flex flex-col min-h-0 animate-panel-in">
      <div className="p-3 border-b border-border animate-blur-rise">
        <input
          className="text-xs text-muted-foreground bg-transparent border-none outline-none mb-2 w-full font-medium"
          value={activeRequest.name}
          onChange={(e) => update({ name: e.target.value })}
          placeholder="Request name"
        />
        <div className="flex items-center gap-2">
          <Select value={activeRequest.method} onValueChange={(value) => update({ method: value as HttpMethod })}>
            <SelectTrigger
              className={cn(
                'h-10 w-[126px] text-xs font-semibold bg-card/80 backdrop-blur-sm transition-all',
                METHOD_COLORS[activeRequest.method]
              )}
            >
              <SelectValue placeholder="Method" />
            </SelectTrigger>
            <SelectContent className="animate-dropdown-blur">
              {METHODS.map((method) => (
                <SelectItem key={method} value={method} className={cn('text-xs font-semibold', METHOD_COLORS[method])}>
                  {method}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <input
            className="flex-1 text-sm bg-card border border-border rounded-md px-3 py-2 outline-none focus:ring-1 focus:ring-ring transition-all font-mono placeholder:text-muted-foreground"
            value={activeRequest.url}
            onChange={(e) => {
              const nextUrl = e.target.value;
              const shouldSyncName = shouldSyncRequestNameWithUrl(activeRequest.name, activeRequest.url);

              update({
                url: nextUrl,
                name: shouldSyncName ? deriveRequestNameFromUrl(nextUrl) : activeRequest.name,
              });
            }}
            placeholder="Enter request URL or paste cURL"
            onKeyDown={(e) => e.key === 'Enter' && sendRequest(activeRequest.id)}
          />
          <button
            onClick={() => sendRequest(activeRequest.id)}
            disabled={isLoading}
            className={cn(
              'inline-flex items-center gap-2 px-5 py-2 rounded-md text-sm font-medium transition-all duration-200',
              'bg-accent text-accent-foreground hover:opacity-90 disabled:opacity-50'
            )}
          >
            {isLoading ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Send className="w-3.5 h-3.5" />
            )}
            Send
          </button>
        </div>
      </div>

      <Tabs defaultValue="params" className="flex-1 flex flex-col min-h-0">
        <TabsList className="mx-3 mt-2 bg-transparent justify-start gap-0 h-auto p-0 border-b border-border rounded-none">
          {['params', 'headers', 'body', 'auth', 'pre-request', 'tests'].map(tab => (
            <TabsTrigger
              key={tab}
              value={tab}
              className="rounded-none border-b-2 border-transparent data-[state=active]:border-accent data-[state=active]:bg-transparent data-[state=active]:shadow-none text-xs capitalize px-3 py-2"
            >
              {tab}
              {tab === 'params' && activeRequest.params.filter(p => p.key).length > 0 && (
                <span className="ml-1.5 text-[10px] bg-accent/10 text-accent px-1.5 rounded-full">
                  {activeRequest.params.filter(p => p.key).length}
                </span>
              )}
              {tab === 'headers' && activeRequest.headers.filter(h => h.key).length > 0 && (
                <span className="ml-1.5 text-[10px] bg-accent/10 text-accent px-1.5 rounded-full">
                  {activeRequest.headers.filter(h => h.key).length}
                </span>
              )}
            </TabsTrigger>
          ))}
        </TabsList>

        <div className="flex-1 min-h-0 overflow-hidden">
          <TabsContent value="params" className="m-0 h-full overflow-y-auto p-3 animate-content-flow">
            <KeyValueEditor
              items={activeRequest.params}
              onChange={(id, u) => updateKeyValue('params', id, u)}
              onAdd={() => addKeyValue('params')}
              onRemove={(id) => removeKeyValue('params', id)}
              onReorder={(fromIndex, toIndex) => reorderKeyValue('params', fromIndex, toIndex)}
            />
          </TabsContent>

          <TabsContent value="headers" className="m-0 h-full overflow-y-auto p-3 animate-content-flow">
            <div className="mb-3 rounded-md border border-border bg-muted/20 p-2.5">
              <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider mb-1.5">
                Auto-Generated Headers
              </p>
              <div className="space-y-1">
                {Object.entries(autoGeneratedHeaders).map(([key, value]) => (
                  <div key={key} className="flex gap-2 text-xs">
                    <span className="font-mono text-foreground/90">{key}</span>
                    <span className="font-mono text-muted-foreground truncate">{value}</span>
                  </div>
                ))}
              </div>
            </div>
            <KeyValueEditor
              items={activeRequest.headers}
              onChange={(id, u) => updateKeyValue('headers', id, u)}
              onAdd={() => addKeyValue('headers')}
              onRemove={(id) => removeKeyValue('headers', id)}
              onReorder={(fromIndex, toIndex) => reorderKeyValue('headers', fromIndex, toIndex)}
            />
          </TabsContent>

          <TabsContent
            value="body"
            className="m-0 h-full p-3 animate-content-flow data-[state=active]:flex data-[state=active]:flex-col"
          >
            <ToggleGroup
              type="single"
              value={activeRequest.bodyType}
              onValueChange={(value) => {
                if (value) {
                  update({ bodyType: value as typeof activeRequest.bodyType });
                }
              }}
              variant="outline"
              size="sm"
              className="justify-start flex-wrap mb-3"
            >
              {(['none', 'json', 'form-data', 'raw', 'graphql'] as const).map(bt => (
                <ToggleGroupItem key={bt} value={bt} className="text-xs capitalize h-8 px-2.5">
                  {bt}
                </ToggleGroupItem>
              ))}
            </ToggleGroup>
            {activeRequest.bodyType !== 'none' && (
              <textarea
                className="w-full flex-1 min-h-[14rem] bg-code-bg text-code-foreground rounded-lg p-4 font-mono text-xs outline-none resize-none overflow-auto border border-border focus:ring-1 focus:ring-ring transition-all"
                value={activeRequest.body}
                onChange={(e) => update({ body: e.target.value })}
                placeholder={activeRequest.bodyType === 'json' ? '{\n  "key": "value"\n}' : activeRequest.bodyType === 'graphql' ? '{\n  query {\n    users {\n      id\n      name\n    }\n  }\n}' : 'Enter request body'}
                spellCheck={false}
              />
            )}
          </TabsContent>

          <TabsContent value="auth" className="m-0 h-full overflow-y-auto p-3 animate-content-flow">
            <div className="space-y-3">
              <Select
                value={activeRequest.auth.type}
                onValueChange={(value) => {
                  update({ auth: { ...activeRequest.auth, type: value as typeof AUTH_TYPES[number] } });
                }}
              >
                <SelectTrigger className="h-9 w-48 text-xs bg-card/80 backdrop-blur-sm">
                  <SelectValue placeholder="Auth type" />
                </SelectTrigger>
                <SelectContent className="animate-dropdown-blur">
                  <SelectItem value="none" className="text-xs">No Auth</SelectItem>
                  <SelectItem value="bearer" className="text-xs">Bearer Token</SelectItem>
                  <SelectItem value="basic" className="text-xs">Basic Auth</SelectItem>
                  <SelectItem value="api-key" className="text-xs">API Key</SelectItem>
                </SelectContent>
              </Select>
              {activeRequest.auth.type === 'bearer' && (
                <input
                  className="w-full text-xs bg-card border border-border rounded-md px-3 py-2 outline-none font-mono"
                  value={activeRequest.auth.token || ''}
                  onChange={(e) => update({ auth: { ...activeRequest.auth, token: e.target.value } })}
                  placeholder="Enter bearer token"
                />
              )}
              {activeRequest.auth.type === 'basic' && (
                <div className="flex gap-2">
                  <input
                    className="flex-1 text-xs bg-card border border-border rounded-md px-3 py-2 outline-none"
                    value={activeRequest.auth.username || ''}
                    onChange={(e) => update({ auth: { ...activeRequest.auth, username: e.target.value } })}
                    placeholder="Username"
                  />
                  <input
                    type="password"
                    className="flex-1 text-xs bg-card border border-border rounded-md px-3 py-2 outline-none"
                    value={activeRequest.auth.password || ''}
                    onChange={(e) => update({ auth: { ...activeRequest.auth, password: e.target.value } })}
                    placeholder="Password"
                  />
                </div>
              )}
              {activeRequest.auth.type === 'api-key' && (
                <div className="flex gap-2">
                  <input
                    className="flex-1 text-xs bg-card border border-border rounded-md px-3 py-2 outline-none"
                    value={activeRequest.auth.key || ''}
                    onChange={(e) => update({ auth: { ...activeRequest.auth, key: e.target.value } })}
                    placeholder="Header name"
                  />
                  <input
                    className="flex-1 text-xs bg-card border border-border rounded-md px-3 py-2 outline-none"
                    value={activeRequest.auth.value || ''}
                    onChange={(e) => update({ auth: { ...activeRequest.auth, value: e.target.value } })}
                    placeholder="Value"
                  />
                </div>
              )}
            </div>
          </TabsContent>

          <TabsContent
            value="pre-request"
            className="m-0 h-full p-3 animate-content-flow data-[state=active]:flex data-[state=active]:flex-col"
          >
            <p className="text-xs text-muted-foreground mb-2">
              JavaScript to run before the request is sent.
            </p>
            <textarea
              className="w-full flex-1 min-h-[14rem] bg-code-bg text-code-foreground rounded-lg p-4 font-mono text-xs outline-none resize-none overflow-auto border border-border"
              value={activeRequest.preRequestScript}
              onChange={(e) => update({ preRequestScript: e.target.value })}
              placeholder={`// Example:\n// pm.environment.set("timestamp", Date.now());`}
              spellCheck={false}
            />
          </TabsContent>

          <TabsContent
            value="tests"
            className="m-0 h-full p-3 animate-content-flow data-[state=active]:flex data-[state=active]:flex-col"
          >
            <p className="text-xs text-muted-foreground mb-2">
              Write tests to validate your response.
            </p>
            <textarea
              className="w-full flex-1 min-h-[14rem] bg-code-bg text-code-foreground rounded-lg p-4 font-mono text-xs outline-none resize-none overflow-auto border border-border"
              value={activeRequest.tests}
              onChange={(e) => update({ tests: e.target.value })}
              placeholder={`// Example:\npm.test("Status is 200", function() {\n  pm.expect(pm.response.code).to.equal(200);\n});`}
              spellCheck={false}
            />
          </TabsContent>
        </div>
      </Tabs>
    </div>
  );
};

function KeyValueEditor({
  items,
  onChange,
  onAdd,
  onRemove,
  onReorder,
}: {
  items: KeyValuePair[];
  onChange: (id: string, updates: Partial<KeyValuePair>) => void;
  onAdd: () => void;
  onRemove: (id: string) => void;
  onReorder: (fromIndex: number, toIndex: number) => void;
}) {
  const [draggingId, setDraggingId] = React.useState<string | null>(null);
  const [dropTargetId, setDropTargetId] = React.useState<string | null>(null);

  const clearDrag = () => {
    setDraggingId(null);
    setDropTargetId(null);
  };

  return (
    <div className="space-y-1.5">
      {items.map((item) => (
        <div
          key={item.id}
          draggable
          onDragStart={() => setDraggingId(item.id)}
          onDragOver={(event) => {
            event.preventDefault();
            if (draggingId && draggingId !== item.id) {
              setDropTargetId(item.id);
            }
          }}
          onDrop={(event) => {
            event.preventDefault();

            if (!draggingId || draggingId === item.id) {
              clearDrag();
              return;
            }

            const fromIndex = items.findIndex(entry => entry.id === draggingId);
            const toIndex = items.findIndex(entry => entry.id === item.id);

            if (fromIndex >= 0 && toIndex >= 0) {
              onReorder(fromIndex, toIndex);
            }

            clearDrag();
          }}
          onDragEnd={clearDrag}
          className={cn(
            'flex items-center gap-2 group rounded-md px-1.5 py-1 transition-colors',
            dropTargetId === item.id ? 'bg-accent/10 ring-1 ring-inset ring-accent/35' : ''
          )}
        >
          <GripVertical className="w-3.5 h-3.5 text-muted-foreground/70 shrink-0 cursor-grab" />
          <Checkbox
            checked={item.enabled}
            onCheckedChange={(checked) => onChange(item.id, { enabled: checked === true })}
            className="border-border data-[state=checked]:bg-accent data-[state=checked]:border-accent"
          />
          <input
            className="flex-1 text-xs bg-card border border-border rounded px-2.5 py-1.5 outline-none focus:ring-1 focus:ring-ring transition-all font-mono"
            value={item.key}
            onChange={(e) => onChange(item.id, { key: e.target.value })}
            placeholder="Key"
          />
          <input
            className="flex-1 text-xs bg-card border border-border rounded px-2.5 py-1.5 outline-none focus:ring-1 focus:ring-ring transition-all font-mono"
            value={item.value}
            onChange={(e) => onChange(item.id, { value: e.target.value })}
            placeholder="Value"
          />
          <button
            onClick={() => onRemove(item.id)}
            className="p-1 rounded opacity-0 group-hover:opacity-100 text-muted-foreground hover:text-destructive transition-all"
          >
            <Trash2 className="w-3 h-3" />
          </button>
        </div>
      ))}
      <button
        onClick={onAdd}
        className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors mt-2"
      >
        <Plus className="w-3 h-3" /> Add row
      </button>
    </div>
  );
}

export default RequestPanel;
