import React, { createContext, useContext, useReducer, useCallback } from 'react';
import {
  ApiRequest, ApiResponse, Collection, Environment, AppTab, TestResult,
  createEmptyRequest, createDefaultEnvironment,
} from '@desktop/types/api';
import { getAutoGeneratedHeaders } from '@desktop/lib/request-utils';

interface AppState {
  collections: Collection[];
  standaloneRequests: ApiRequest[];
  environments: Environment[];
  tabs: AppTab[];
  activeTabId: string | null;
  requests: Record<string, ApiRequest>;
  responses: Record<string, ApiResponse | null>;
  testResults: Record<string, TestResult[]>;
  loading: Record<string, boolean>;
  sidebarCollapsed: boolean;
}

type Action =
  | { type: 'ADD_COLLECTION'; payload: Collection }
  | { type: 'DELETE_COLLECTION'; payload: string }
  | { type: 'UPDATE_COLLECTION'; payload: { collectionId: string; name: string } }
  | { type: 'TOGGLE_COLLECTION'; payload: string }
  | { type: 'REORDER_COLLECTIONS'; payload: { fromIndex: number; toIndex: number } }
  | { type: 'ADD_REQUEST'; payload: { request: ApiRequest; collectionId?: string | null } }
  | { type: 'UPDATE_REQUEST'; payload: ApiRequest }
  | { type: 'DELETE_REQUEST'; payload: { requestId: string; collectionId?: string | null } }
  | {
      type: 'REORDER_REQUESTS';
      payload: {
        fromCollectionId?: string | null;
        toCollectionId?: string | null;
        fromIndex: number;
        toIndex: number;
      };
    }
  | { type: 'OPEN_TAB'; payload: AppTab }
  | { type: 'CLOSE_TAB'; payload: string }
  | { type: 'SET_ACTIVE_TAB'; payload: string }
  | { type: 'SET_RESPONSE'; payload: { requestId: string; response: ApiResponse | null } }
  | { type: 'SET_LOADING'; payload: { requestId: string; loading: boolean } }
  | { type: 'SET_TEST_RESULTS'; payload: { requestId: string; results: TestResult[] } }
  | { type: 'SET_ACTIVE_ENV'; payload: string }
  | { type: 'UPDATE_ENVIRONMENT'; payload: Environment }
  | { type: 'TOGGLE_SIDEBAR' };

const defaultRequest = createEmptyRequest();

const initialState: AppState = {
  collections: [],
  standaloneRequests: [defaultRequest],
  environments: createDefaultEnvironment(),
  tabs: [{ id: defaultRequest.id, requestId: defaultRequest.id, name: defaultRequest.name, method: defaultRequest.method }],
  activeTabId: defaultRequest.id,
  requests: { [defaultRequest.id]: defaultRequest },
  responses: {},
  testResults: {},
  loading: {},
  sidebarCollapsed: false,
};

const reorderItems = <T,>(items: T[], fromIndex: number, toIndex: number): T[] => {
  const copy = [...items];
  const [moved] = copy.splice(fromIndex, 1);

  if (moved === undefined) {
    return items;
  }

  copy.splice(toIndex, 0, moved);
  return copy;
};

function reducer(state: AppState, action: Action): AppState {
  switch (action.type) {
    case 'ADD_COLLECTION':
      return { ...state, collections: [...state.collections, action.payload] };
    case 'DELETE_COLLECTION': {
      const collectionToDelete = state.collections.find(collection => collection.id === action.payload);

      if (!collectionToDelete) {
        return state;
      }

      return {
        ...state,
        collections: state.collections.filter(collection => collection.id !== action.payload),
        standaloneRequests: [...state.standaloneRequests, ...collectionToDelete.requests],
      };
    }
    case 'UPDATE_COLLECTION':
      return {
        ...state,
        collections: state.collections.map(collection =>
          collection.id === action.payload.collectionId
            ? { ...collection, name: action.payload.name }
            : collection
        ),
      };
    case 'TOGGLE_COLLECTION':
      return {
        ...state,
        collections: state.collections.map(c =>
          c.id === action.payload ? { ...c, expanded: !c.expanded } : c
        ),
      };
    case 'REORDER_COLLECTIONS': {
      const { fromIndex, toIndex } = action.payload;

      if (
        fromIndex === toIndex ||
        fromIndex < 0 ||
        toIndex < 0 ||
        fromIndex >= state.collections.length ||
        toIndex >= state.collections.length
      ) {
        return state;
      }

      return {
        ...state,
        collections: reorderItems(state.collections, fromIndex, toIndex),
      };
    }
    case 'ADD_REQUEST': {
      const req = action.payload.request;

      if (!action.payload.collectionId) {
        return {
          ...state,
          standaloneRequests: [...state.standaloneRequests, req],
          requests: { ...state.requests, [req.id]: req },
        };
      }

      return {
        ...state,
        collections: state.collections.map(c =>
          c.id === action.payload.collectionId
            ? { ...c, requests: [...c.requests, req] }
            : c
        ),
        requests: { ...state.requests, [req.id]: req },
      };
    }
    case 'REORDER_REQUESTS': {
      const { fromCollectionId, toCollectionId, fromIndex, toIndex } = action.payload;
      const sourceIsStandalone = !fromCollectionId;
      const targetIsStandalone = !toCollectionId;

      const sourceRequests = sourceIsStandalone
        ? state.standaloneRequests
        : (state.collections.find(c => c.id === fromCollectionId)?.requests ?? null);
      const targetRequests = targetIsStandalone
        ? state.standaloneRequests
        : (state.collections.find(c => c.id === toCollectionId)?.requests ?? null);

      if (!sourceRequests || !targetRequests) {
        return state;
      }

      if (fromIndex < 0 || fromIndex >= sourceRequests.length) {
        return state;
      }

      if (fromCollectionId === toCollectionId) {
        if (
          toIndex < 0 ||
          toIndex >= sourceRequests.length ||
          fromIndex === toIndex
        ) {
          return state;
        }

        if (sourceIsStandalone) {
          return {
            ...state,
            standaloneRequests: reorderItems(state.standaloneRequests, fromIndex, toIndex),
          };
        }

        return {
          ...state,
          collections: state.collections.map(collection => {
            if (collection.id !== fromCollectionId) {
              return collection;
            }

            return {
              ...collection,
              requests: reorderItems(collection.requests, fromIndex, toIndex),
            };
          }),
        };
      }

      const movedRequest = sourceRequests[fromIndex];
      const boundedTargetIndex = Math.max(0, Math.min(toIndex, targetRequests.length));
      const nextStandaloneRequests = [...state.standaloneRequests];

      if (sourceIsStandalone) {
        nextStandaloneRequests.splice(fromIndex, 1);
      }

      if (targetIsStandalone) {
        nextStandaloneRequests.splice(boundedTargetIndex, 0, movedRequest);
      }

      return {
        ...state,
        standaloneRequests: nextStandaloneRequests,
        collections: state.collections.map(collection => {
          if (!sourceIsStandalone && collection.id === fromCollectionId) {
            return {
              ...collection,
              requests: collection.requests.filter((_, idx) => idx !== fromIndex),
            };
          }

          if (!targetIsStandalone && collection.id === toCollectionId) {
            const requests = [...collection.requests];
            requests.splice(boundedTargetIndex, 0, movedRequest);
            return { ...collection, requests };
          }

          return collection;
        }),
      };
    }
    case 'UPDATE_REQUEST':
      return {
        ...state,
        requests: { ...state.requests, [action.payload.id]: action.payload },
        standaloneRequests: state.standaloneRequests.map(request =>
          request.id === action.payload.id ? action.payload : request
        ),
        collections: state.collections.map(collection => ({
          ...collection,
          requests: collection.requests.map(request =>
            request.id === action.payload.id ? action.payload : request
          ),
        })),
        tabs: state.tabs.map(t =>
          t.requestId === action.payload.id
            ? { ...t, name: action.payload.name, method: action.payload.method, dirty: true }
            : t
        ),
      };
    case 'DELETE_REQUEST': {
      const newTabs = state.tabs.filter(t => t.requestId !== action.payload.requestId);
      const newRequests = { ...state.requests };
      const newResponses = { ...state.responses };
      const newTestResults = { ...state.testResults };
      const newLoading = { ...state.loading };

      delete newRequests[action.payload.requestId];
      delete newResponses[action.payload.requestId];
      delete newTestResults[action.payload.requestId];
      delete newLoading[action.payload.requestId];

      const standaloneRequests = action.payload.collectionId
        ? state.standaloneRequests
        : state.standaloneRequests.filter(r => r.id !== action.payload.requestId);

      return {
        ...state,
        standaloneRequests,
        collections: state.collections.map(c =>
          c.id === action.payload.collectionId
            ? { ...c, requests: c.requests.filter(r => r.id !== action.payload.requestId) }
            : c
        ),
        tabs: newTabs,
        activeTabId: state.activeTabId === action.payload.requestId
          ? (newTabs[newTabs.length - 1]?.id ?? null)
          : state.activeTabId,
        requests: newRequests,
        responses: newResponses,
        testResults: newTestResults,
        loading: newLoading,
      };
    }
    case 'OPEN_TAB': {
      const exists = state.tabs.find(t => t.id === action.payload.id);
      if (exists) return { ...state, activeTabId: action.payload.id };
      return { ...state, tabs: [...state.tabs, action.payload], activeTabId: action.payload.id };
    }
    case 'CLOSE_TAB': {
      const filtered = state.tabs.filter(t => t.id !== action.payload);
      return {
        ...state,
        tabs: filtered,
        activeTabId: state.activeTabId === action.payload
          ? (filtered[filtered.length - 1]?.id ?? null)
          : state.activeTabId,
      };
    }
    case 'SET_ACTIVE_TAB':
      return { ...state, activeTabId: action.payload };
    case 'SET_RESPONSE':
      return { ...state, responses: { ...state.responses, [action.payload.requestId]: action.payload.response } };
    case 'SET_LOADING':
      return { ...state, loading: { ...state.loading, [action.payload.requestId]: action.payload.loading } };
    case 'SET_TEST_RESULTS':
      return { ...state, testResults: { ...state.testResults, [action.payload.requestId]: action.payload.results } };
    case 'SET_ACTIVE_ENV':
      return {
        ...state,
        environments: state.environments.map(e => ({ ...e, active: e.id === action.payload })),
      };
    case 'UPDATE_ENVIRONMENT':
      return {
        ...state,
        environments: state.environments.map(e => e.id === action.payload.id ? action.payload : e),
      };
    case 'TOGGLE_SIDEBAR':
      return { ...state, sidebarCollapsed: !state.sidebarCollapsed };
    default:
      return state;
  }
}

interface AppContextValue {
  state: AppState;
  dispatch: React.Dispatch<Action>;
  createRequest: (collectionId?: string | null) => ApiRequest;
  sendRequest: (requestId: string) => Promise<void>;
}

const AppContext = createContext<AppContextValue | null>(null);

const getErrorMessage = (error: unknown) => {
  return error instanceof Error ? error.message : 'Request failed';
};

const getRequestSendErrorMessage = (error: unknown) => {
  const fallback = 'Could not send request.';

  if (!(error instanceof Error)) {
    return fallback;
  }

  const message = error.message?.trim();
  if (!message) {
    return fallback;
  }

  const normalized = message.toLowerCase();
  if (
    normalized.includes('fetch failed') ||
    normalized.includes('failed to fetch') ||
    normalized.includes('networkerror') ||
    normalized.includes('econn') ||
    normalized.includes('enotfound') ||
    normalized.includes('eai_again') ||
    normalized.includes('timed out') ||
    normalized.includes('socket hang up')
  ) {
    return fallback;
  }

  return message;
};

const getBridgeUnavailableMessage = () => {
  return 'Desktop bridge unavailable. Run flav with npm run dev:desktop or use the packaged flav.exe.';
};

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [state, dispatch] = useReducer(reducer, initialState);

  const createRequest = useCallback((collectionId?: string | null) => {
    const request = createEmptyRequest();

    dispatch({ type: 'ADD_REQUEST', payload: { collectionId: collectionId ?? null, request } });
    dispatch({
      type: 'OPEN_TAB',
      payload: { id: request.id, requestId: request.id, name: request.name, method: request.method },
    });

    return request;
  }, []);

  const sendRequest = useCallback(async (requestId: string) => {
    const request = state.requests[requestId];
    if (!request) return;

    dispatch({ type: 'SET_LOADING', payload: { requestId, loading: true } });
    dispatch({ type: 'SET_RESPONSE', payload: { requestId, response: null } });

    const startTime = performance.now();

    try {
      // Replace environment variables
      const activeEnv = state.environments.find(e => e.active);
      let url = request.url;
      if (activeEnv) {
        activeEnv.variables.forEach(v => {
          if (v.enabled && v.key) {
            url = url.replace(`{{${v.key}}}`, v.value);
          }
        });
      }

      // Build query params
      const enabledParams = request.params.filter(p => p.enabled && p.key);
      if (enabledParams.length > 0) {
        const searchParams = new URLSearchParams();
        enabledParams.forEach(p => searchParams.append(p.key, p.value));
        url += (url.includes('?') ? '&' : '?') + searchParams.toString();
      }

      // Build headers
      const headers: Record<string, string> = {};
      request.headers.filter(h => h.enabled && h.key).forEach(h => {
        headers[h.key] = h.value;
      });

      const manualHeaderNames = new Set(Object.keys(headers).map(key => key.toLowerCase()));
      const autoHeaders = getAutoGeneratedHeaders(request);

      Object.entries(autoHeaders).forEach(([key, value]) => {
        if (!manualHeaderNames.has(key.toLowerCase())) {
          headers[key] = value;
        }
      });

      if (request.auth.type === 'bearer' && request.auth.token) {
        headers.Authorization = autoHeaders.Authorization;
      } else if (request.auth.type === 'basic' && request.auth.username) {
        headers.Authorization = autoHeaders.Authorization;
      } else if (request.auth.type === 'api-key' && request.auth.key) {
        headers[request.auth.key] = autoHeaders[request.auth.key];
      }

      const options: RequestInit = {
        method: request.method,
        headers,
      };

      if (!['GET', 'HEAD'].includes(request.method) && request.body && request.bodyType !== 'none') {
        options.body = request.body;
      }

        if (!url.trim()) {
          throw new Error('Request URL is required.');
        }

        if (!window.arcApi?.sendRequest) {
          throw new Error(getBridgeUnavailableMessage());
        }

      let bodyText = '';
      let status = 0;
      let statusText = 'Error';
      let elapsed = 0;
      let responseSize = 0;
      const responseHeaders: Record<string, string> = {};

        const desktopResponse = await window.arcApi.sendRequest({
          url,
          method: request.method,
          headers,
          body: typeof options.body === 'string' ? options.body : undefined,
        });

        if (!desktopResponse.ok) {
          throw new Error(desktopResponse.error || 'Request failed');
      }

        bodyText = desktopResponse.body;
        status = desktopResponse.status;
        statusText = desktopResponse.statusText;
        elapsed = desktopResponse.time;
        responseSize = desktopResponse.size;
        Object.assign(responseHeaders, desktopResponse.headers);

      const response = {
        status,
        statusText,
        headers: responseHeaders,
        body: bodyText,
        time: elapsed,
        size: responseSize,
      };

      dispatch({ type: 'SET_RESPONSE', payload: { requestId, response } });

      // Run basic test assertions
      if (request.tests.trim()) {
        try {
          const results: TestResult[] = [];
          const testFn = new Function(
            'pm',
            request.tests
          );
          const pm = {
            response: {
              code: response.status,
              status: response.statusText,
              body: bodyText,
              json: () => { try { return JSON.parse(bodyText); } catch { return null; } },
              headers: responseHeaders,
              responseTime: response.time,
            },
            test: (name: string, fn: () => void) => {
              try { fn(); results.push({ name, passed: true }); }
              catch (error: unknown) { results.push({ name, passed: false, message: getErrorMessage(error) }); }
            },
            expect: (val: unknown) => ({
              to: {
                equal: (expected: unknown) => { if (val !== expected) throw new Error(`Expected ${expected} but got ${val}`); },
                be: {
                  above: (n: number) => {
                    if (typeof val !== 'number' || val <= n) {
                      throw new Error(`Expected > ${n} but got ${val}`);
                    }
                  },
                  below: (n: number) => {
                    if (typeof val !== 'number' || val >= n) {
                      throw new Error(`Expected < ${n} but got ${val}`);
                    }
                  },
                  true: val === true ? undefined : (() => { throw new Error(`Expected true but got ${val}`); })(),
                },
                include: (str: string) => { if (!String(val).includes(str)) throw new Error(`Expected to include "${str}"`); },
                have: {
                  status: (code: number) => { if (response.status !== code) throw new Error(`Expected status ${code} but got ${response.status}`); },
                },
              },
            }),
          };
          testFn(pm);
          dispatch({ type: 'SET_TEST_RESULTS', payload: { requestId, results } });
        } catch (error: unknown) {
          dispatch({ type: 'SET_TEST_RESULTS', payload: { requestId, results: [{ name: 'Script Error', passed: false, message: getErrorMessage(error) }] } });
        }
      }
    } catch (error: unknown) {
      const endTime = performance.now();
      dispatch({
        type: 'SET_RESPONSE',
        payload: {
          requestId,
          response: {
            status: 0,
            statusText: 'Error',
            headers: {},
            body: getRequestSendErrorMessage(error),
            time: Math.round(endTime - startTime),
            size: 0,
          },
        },
      });
    } finally {
      dispatch({ type: 'SET_LOADING', payload: { requestId, loading: false } });
    }
  }, [state.requests, state.environments]);

  return (
    <AppContext.Provider value={{ state, dispatch, createRequest, sendRequest }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}
